# https://golang.github.io/dep/docs/Gopkg.toml.html

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.35.1"

[[constraint]]
  name = "github.com/rs/xid"
  version = "1.2.1"
