apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: rule-3-weight50
spec:
  destination:
    name: user
    namespace: reactor
  precedence: 2
  route:
  - labels:
      version: '2'
    weight: 50
  - labels:
      version: '1'
    weight: 50
