apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: rule-5-a-fail
spec:
  destination:
    name: a
    namespace: reactor
  precedence: 2
  route:
  - labels:
      version: '1'
    weight: 100
  httpFault:
    abort:
      percent: 60
      httpStatus: 500
