apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: rule-6-b-delay
spec:
  destination:
    name: b
    namespace: reactor
  precedence: 2
  route:
  - labels:
      version: '1'
    weight: 100
  httpFault:
    delay:
      percent: 75
      fixedDelay: 5s
